version: "3"

services:
  postgres:
    container_name: cloud-file-storage
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=cloud-file-storage
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5440:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioroot
      - MINIO_ROOT_PASSWORD=minioroot
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio

volumes:
  dbdata:
    driver: local
  minio-data:
    driver: local

