spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
  data:
    redis:
      host: localhost
      port: 6379
      password: root

  flyway:
    enabled: true
    locations: classpath:migration

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  thymeleaf:
    encoding: UTF-8

  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8


minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
